#TODO 

FIX POLARS DB QUERY:
    Traceback (most recent call last):
    File "src/main.py", line 18, in <module>
        main()
    File "src/main.py", line 11, in main
        generate_sample_contract_report(conn)
    File "/app/src/utils/report.py", line 43, in generate_sample_contract_report
        df = pl.read_sql(query, conn)
    File "/usr/local/lib/python3.8/dist-packages/polars/__init__.py", line 416, in __getattr__
        raise AttributeError(msg)
    AttributeError: module 'polars' has no attribute 'read_sql'